# Site settings
title: Redirecting
baseurl: "/debugger-protocol-viewer"
url: "https://chromedevtools.github.io"

collections:
  versions:
    output: true
    permalink: /:path/
  domains:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
    type: versions
  values:
    layout: default
- scope:
    path: ""
    type: domains
  values:
    layout: default

gems:
  - jekyll-redirect-from
